### ISSUE TITLE
Update the readme

### ISSUE THREAD

**Issue by 20jasper** [20jasper/budget-tracker#1]
- [x] change title
- [x] update tech used
- [x] optimizations
- [x] lessons learned

**Comment by devd00** [comment]
I can help you with that

**Comment by TCHProductions** [comment]
leaving comment

**Comment by bycarlosgamez** [comment]
let's do this! :)

**Comment by 20jasper** [comment]
In PR #22 I fixed some typos and added a new lesson learned

**Comment by NPMaiorano** [comment]
Thanks for fixing those typos and adding to lessons learned
